version: "3.2"
services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: 'oracle-db'
    ports:
        - 1521:1521
        - 8080:8080
    environment:
            - ORACLE_PASSWORD=Promeni1!
    restart: "always"


networks:
 default:
   external: 
     name: ${NETWORK}
