version: "3.2"
services:
  event-ticket:
    image: event-ticket
    container_name: 'event-ticket'
    ports:
        - 8080:8080
    volumes:
        - ~/.docker-conf/event-ticket/data/:/home/upoznat/event-ticket/lib
        - ~/.docker-conf/event-ticket/log/:/home/upoznat/event-ticket/log
    networks:
        - eventer_net
        
  wallet:
    image: wallet
    container_name: 'wallet'
    ports:
        - 8081:8081
    volumes:
        - ~/.docker-conf/wallet/data/:/home/upoznat/wallet/lib
        - ~/.docker-conf/wallet/log/:/home/upoznat/wallet/log
    networks:
        - eventer_net

  payment-service:
    image: payment-service
    container_name: 'payment-service'
    ports:
        - 8082:8082
    volumes:
        - ~/.docker-conf/payment-service/data/:/home/upoznat/payment-service/lib
        - ~/.docker-conf/payment-service/log/:/home/upoznat/payment-service/log
    networks:
        - eventer_net

networks:
  eventer_net:
    external: true
    



