version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
        - 15691:15692
        - 9419:9419
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/home/upoznat/rabbitmq/lib
        - ~/.docker-conf/rabbitmq/log/:/home/upoznat/rabbitmq/log

networks:
 default:
   external: 
     name: ${NETWORK}
    



