version: "3.2"
services:
  payment-service:
    image: payment-service
    container_name: 'payment-service'
    ports:
        - 8082:8082
    network_mode: eventer-net
    volumes:
        - ~/.docker-conf/payment-service/data/:/home/upoznat/payment-service/lib
        - ~/.docker-conf/payment-service/log/:/home/upoznat/payment-service/log
    

    



